# Resolução quebra cabeça 9 peças

In [ ]:
import numpy as np

## Classe para o problema

In [ ]:
class SlidingPuzzle():
  def __init__(self, num_blocks):
    self.num_blocks = num_blocks    # tamanho do puzze que é 3/3 = 9 peças

    #procurando um numero na matriz por exemplo aonde esta o numero 5 na Matriz que pode ser na linha 2 coluna 1 [2,1] =5
  def _search_position(self, state, element):
    for i in range(self.num_blocks):
      for j in range(self.num_blocks):
        if state[i, j] == element:  # exemplo se [2,3] == 5 
          return i, j
    
    return None, None  #nao encontro o elemento na matriz

  #verificando se cheguei no que quero no jogo / estado objetivo onde todas peças estao corretas 
  def verify_states(self, current, target):    #current  = estado atual  , target = estado objetivo
    flag = True   # esta no estado objetivo?

    #for das linhas
    for i in range(self.num_blocks):
      if not flag:  # se a flag ja tiver com false ja pode parar esse for
        break

      for j in range(self.num_blocks):
        # se a matriz na posição i j tiver diferente do objetivo ja pode parar que nao é o objetivo
        if current[i, j] != target[i, j]:
          flag = False # ja sai do segundo for e volta pro primeiro
          break

    return flag

   # pra expandir o estado ver a possibilidade de movimento da matriz
  def expand_state(self, current):
    new_states = []

    line, column = self._search_position(current, 0)  # procurando aonde esta o ZERO na matriz e guardando na linha,coluna

    #provavelmente entrara em todos IFS
    #cima
    if line > 0:  # pra nao pegar posição -1 q nao existe na matriz
      new_line = line - 1   #nova linha onde vai o ZERO
      new_state = np.copy(current)   # copiando a matriz atual

      target_block = new_state[new_line, column]   # armazenando o valor que esta nessa posiçao |||exemplo target_block=new_state[0,1] = 5
      new_state[new_line, column] = 0              # colocando o zero na nova posiçao, que tirou o numero |||exemplo new_state[0,1] = 0
      new_state[line, column] = target_block       # colocando o valor aonde estava o zero |||exemplo new_state[1,1] = 5

      new_states.append(new_state)    # novo estado da matriz

    # Baixo
    if line < self.num_blocks - 1:
      new_line = line + 1
      new_state = np.copy(current)

      target_block = new_state[new_line, column] # 2 
      new_state[new_line, column] = 0
      new_state[line, column] = target_block

      new_states.append(new_state)

    # Esquerda
    if column > 0:
      new_column = column - 1
      new_state = np.copy(current)

      target_block = new_state[line, new_column] 
      new_state[line, new_column] = 0
      new_state[line, column] = target_block

      new_states.append(new_state)

    # Direita
    if column < self.num_blocks - 1:
      new_column = column + 1
      new_state = np.copy(current)

      target_block = new_state[line, new_column] 
      new_state[line, new_column] = 0
      new_state[line, column] = target_block

      new_states.append(new_state)

    return new_states


## Breadth Firts Search ( BFS )

In [ ]:
from queue import Queue

In [ ]:
class BreadthFirstSearch():
  def __init__(self, problem):
    self.problem = problem

  def _verify_visited(self, state, states_visited):
    for i in states_visited:
      if self.problem.verify_states(i, state):
        return True
    
    return False

  def search(self, start, target):
    queue = Queue()
    queue.put(start) # Insert start in queue

    solution_found = False
    states_visited = []
    count_states = 0

    while not queue.empty():
      current = queue.get() # get first element and delete of queue

      states_visited.append(current)

      if self.problem.verify_states(current, target):
        solution_found = True
        break

      else:
        count_states += 1
        print(f"Visiting state #{count_states}")
        new_states = self.problem.expand_state(current)

        for i in new_states:
          if not self._verify_visited(i, states_visited):
            print(i)
            queue.put(i)

    return solution_found, states_visited, count_states

# Main

In [ ]:
start = np.matrix([
                   [7, 2, 4],
                   [5, 0, 6],
                   [8, 3, 1]
                  ])

target = np.matrix([
                   [0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]
                  ])

print(f"start:\n{start}\n")
print(f"target:\n{target}\n")

start:
[[7 2 4]
 [5 0 6]
 [8 3 1]]

target:
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [ ]:
problem = SlidingPuzzle(3)
bfs = BreadthFirstSearch(problem)

In [ ]:
#com a Busca gulosa o resultado eh encontado mais facil pois a busca gulosa sabe pra onde ela ta indo / ao contrario da busca cega
solution, steps, quantity = bfs.search(start, target)

if solution:
  print(f"Solution found with {quantity} steps")
else:
  print("Solution not found")

Visiting state #1
[[7 0 4]
 [5 2 6]
 [8 3 1]]
[[7 2 4]
 [5 3 6]
 [8 0 1]]
[[7 2 4]
 [0 5 6]
 [8 3 1]]
[[7 2 4]
 [5 6 0]
 [8 3 1]]
Visiting state #2
[[0 7 4]
 [5 2 6]
 [8 3 1]]
[[7 4 0]
 [5 2 6]
 [8 3 1]]
Visiting state #3
[[7 2 4]
 [5 3 6]
 [0 8 1]]
[[7 2 4]
 [5 3 6]
 [8 1 0]]
Visiting state #4
[[0 2 4]
 [7 5 6]
 [8 3 1]]
[[7 2 4]
 [8 5 6]
 [0 3 1]]
Visiting state #5
[[7 2 0]
 [5 6 4]
 [8 3 1]]
[[7 2 4]
 [5 6 1]
 [8 3 0]]
Visiting state #6
[[5 7 4]
 [0 2 6]
 [8 3 1]]
Visiting state #7
[[7 4 6]
 [5 2 0]
 [8 3 1]]
Visiting state #8
[[7 2 4]
 [0 3 6]
 [5 8 1]]
Visiting state #9
[[7 2 4]
 [5 3 0]
 [8 1 6]]
Visiting state #10
[[2 0 4]
 [7 5 6]
 [8 3 1]]
Visiting state #11
[[7 2 4]
 [8 5 6]
 [3 0 1]]
Visiting state #12
[[7 0 2]
 [5 6 4]
 [8 3 1]]
Visiting state #13
[[7 2 4]
 [5 6 1]
 [8 0 3]]
Visiting state #14
[[5 7 4]
 [8 2 6]
 [0 3 1]]
[[5 7 4]
 [2 0 6]
 [8 3 1]]
Visiting state #15
[[7 4 6]
 [5 2 1]
 [8 3 0]]
[[7 4 6]
 [5 0 2]
 [8 3 1]]
Visiting state #16
[[0 2 4]
 [7 3 6]
 [5 8 1]]
[[7 2

KeyboardInterrupt: ignored