# Classe do Problema

In [ ]:
class SlidingPuzzle():
  def __init__(self, num_blocks):
    self.num_blocks = num_blocks

  def _search_position(self, state, element):
    for i in range(self.num_blocks):
      for j in range(self.num_blocks):
        if state[i, j] == element:
          return i, j
    return None, None

  def verify_states(self, current, target):
    flag = True

    for i in range(self.num_blocks):
      if not flag:
        break

      for j in range(self.num_blocks):
        if current[i, j] != target[i, j]:
          flag = False
          break
    return flag

  def expand_state(self, current):
    new_states = []

    line, column = self._search_position(current, 0)

    # to up
    if line > 0:
      new_line = line - 1
      new_state = np.copy(current)

      target_block = new_state[new_line, column]
      new_state[new_line, column] = 0
      new_state[line, column] = target_block

      new_states.append(new_state)

    # to down
    if line < self.num_blocks - 1:
      new_line = line + 1
      new_state = np.copy(current)

      target_block = new_state[new_line, column]
      new_state[new_line, column] = 0
      new_state[line, column] = target_block

      new_states.append(new_state)

    # to left
    if column > 0:
      new_column = column - 1
      new_state = np.copy(current)

      target_block = new_state[line, new_column]
      new_state[line, new_column] = 0
      new_state[line, column] = target_block

      new_states.append(new_state)

    # to right
    if column < self.num_blocks - 1:
      new_column = column + 1
      new_state = np.copy(current)
   
      target_block = new_state[line, new_column]
      new_state[line, new_column] = 0
      new_state[line, column] = target_block

      new_states.append(new_state)

    return new_states

  def manhattanDistance(self, current, target):
    total_dist = 0

    for i in range(self.num_blocks):
      for j in range(self.num_blocks):
        element = current[i, j]
        line, column = self._search_position(target, element)

        dist = abs(line - i) + abs(column - j)
        total_dist += dist

    return total_dist


## Busca Gulosa

In [ ]:
import heapq 

class GreedySearch():
  def __init__(self, problem):
    self.problem = problem

  def _verify_visited(self, state, states_visited):
    for i in states_visited:
      if self.problem.verify_states(i, state):
        return True
    return False

  def search(self, start, tarteg):
    p_queue = [] # priority queue

    # H, ID, state
    heapq.heappush(p_queue, (0, 0, start))

    state_id = 0
    solution_found = False
    states_visited = []
    count_states = 0

    while len(p_queue) != 0:
      current = heapq.heappop(p_queue)[2]
      states_visited.append(current)

      if self.problem.verify_states(current, target):
        solution_found = True
        break
      
      else:
        count_states += 1
        print(f"Visitando #{count_states}")

        new_states = self.problem.expand_state(current)

        for i in new_states:
          if not self._verify_visited(i, states_visited):
            state_id += 1
            priority = self.problem.manhattanDistance(i, target)

            print(f"{i}\nh = {priority}")

            heapq.heappush(p_queue, (priority, state_id, i))

    return solution_found, states_visited, count_states  
        

# Main

In [ ]:
import numpy as np

problem = SlidingPuzzle(3)

start = np.matrix([[2, 8, 3], [1, 6, 4], [7, 5, 0]])
target = np.matrix([[1, 2, 3], [8, 0, 4], [7, 6, 5]])

print(f"start:\n {start}\n")
print(f"target:\n {target}")

start:
 [[2 8 3]
 [1 6 4]
 [7 5 0]]

target:
 [[1 2 3]
 [8 0 4]
 [7 6 5]]


In [ ]:
greedy_search = GreedySearch(problem)
solution, states_visited, steps = greedy_search.search(start, target)

if solution:
  print(f"Solution found with {steps} steps")
else:
  print("Solution not found")

Visitando #1
[[2 8 3]
 [1 6 0]
 [7 5 4]]
h = 8
[[2 8 3]
 [1 6 4]
 [7 0 5]]
h = 6
Visitando #2
[[2 8 3]
 [1 0 4]
 [7 6 5]]
h = 4
[[2 8 3]
 [1 6 4]
 [0 7 5]]
h = 8
Visitando #3
[[2 0 3]
 [1 8 4]
 [7 6 5]]
h = 4
[[2 8 3]
 [0 1 4]
 [7 6 5]]
h = 6
[[2 8 3]
 [1 4 0]
 [7 6 5]]
h = 6
Visitando #4
[[0 2 3]
 [1 8 4]
 [7 6 5]]
h = 4
[[2 3 0]
 [1 8 4]
 [7 6 5]]
h = 6
Visitando #5
[[1 2 3]
 [0 8 4]
 [7 6 5]]
h = 2
Visitando #6
[[1 2 3]
 [7 8 4]
 [0 6 5]]
h = 4
[[1 2 3]
 [8 0 4]
 [7 6 5]]
h = 0
Solution found with 6 steps
